version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: ttpclub-postgres
    restart: always
    environment:
      POSTGRES_USER: admin_ttpclub
      POSTGRES_PASSWORD: pc101w
      POSTGRES_DB: ttpclub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:


