version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: ttpclub-postgres
    restart: always
    environment:
      POSTGRES_USER: admin_ttpclub
      POSTGRES_PASSWORD: pc101w
      POSTGRES_DB: ttpclub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./ttpclub
    container_name: ttpclub-server
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ttpclub_db
      SPRING_DATASOURCE_USERNAME: admin_ttpclub
      SPRING_DATASOURCE_PASSWORD: pc101w
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ~/Downloads:/host_downloads
  
  client:
    build: ./client_ttpclub
    container_name: ttpclub_client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  postgres_data: