spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ttpclub_db
    username: admin_ttpclub
    password: pc101w
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/Scripts/Script.sql